<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <RootNamespace>ObjektRT.Stdlib</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ObjektRT.Core\ObjektRT.Core.csproj" />
  </ItemGroup>

</Project>
